sudo: required
services:
  - docker

before_install:
  - docker build -t drcylau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true drcylau/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "docker-env-2.eba-qjfmrnjg.eu-north-1.elasticbeanstalk.com"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"